version: '3.1'
networks:
  userservice:
    driver: bridge
  gameservice:
    driver: bridge
  db:
    driver: bridge
  ufront:
    driver: bridge
  gfront:
    driver: bridge

volumes:
  user_mongodb_data:
  user_mongodb_configdata:
  game_mongodb_data:
  game_mongodb_configdata:

services:
  userservice:
    container_name: userservice
    build:
      context: ./userservice/
      dockerfile: Dockerfile
    depends_on:
      - usermongo
    volumes:
      - .:/src
    command: npm start
    ports:
      - '3000:8080'
    environment:
      NODE_ENV: production
      NODE_CONFIG_DIR: ./src/config/
    networks:
      - userservice
      - ufront

  gameservice:
    container_name: gameservice
    build:
      context: ./gameservice/
      dockerfile: Dockerfile
    depends_on:
      - gamemongo
    volumes:
      - .:/src
    command: npm start
    ports:
      - '3001:8080'
    environment:
      DATABASE: mongodb://gs_admin:<PASSWORD>@gamemongo:27017/gameservice
      PORT: 8080
      DATABASE_USERNAME: gs_admin
      DATABASE_PASSWORD: root
      NODE_ENV: production
      NODE_CONFIG_DIR: ./src/config/
    networks:
      - gameservice
      - gfront

  usermongo:
    container_name: usermongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    networks:
      - db
      - userservice
    volumes:
      - user_mongodb_data:/data/db
      - user_mongodb_configdata:/data/configdb
      - ./mongo-init-users.js:/docker-entrypoint-initdb.d/mongo-init-users.js:ro


  gamemongo:
    container_name: gamemongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    networks:
      - gameservice
    volumes:
      - game_mongodb_data:/data/db
      - game_mongodb_configdata:/data/configdb
      - ./mongo-init-games.js:/docker-entrypoint-initdb.d/mongo-init-games.js:ro


  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@usermongo:27017
    depends_on:
      - usermongo
    networks:
      - db

  peerserver:
    container_name: peerserver
    image: peerjs/peerjs-server:latest
    ports:
      - '9000:9000'


  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - gameservice
      - userservice
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '5173:80'
    networks:
      - ufront
      - gfront
