@startuml component
skinparam linetype ortho

[      reverse_proxy       ] as rp
[userservice] as us #GreenYellow
[frontend] as fs #GreenYellow
[peerserver] as ps
[gameservice] as gs #GreenYellow
database "user\nmongo" as udb
database "game\nmongo" as gdb
database "redis" as redis
database "redissocket" as redissocket
actor "Client" as c1

c1 <--- rp: Responses
rp <--- c1: Requests\n\n\n\n\n\n\n

gs <---> rp: HTTP: /api/v1/games\nWebsocket: /socketio/v1\n
us <---> rp: HTTP: /api/v1/users\n\n\n\n
ps <---> rp: HTTP & Websocket:\n/peerserver\n\n\n\n
fs <---> rp: HTTP: /*
udb <-- us
redis <-- us
gdb <-- gs
redissocket <-- gs
@enduml