@startuml component
skinparam linetype ortho

[      NGINX       ] as rp
[userservice] as us
[frontend] as fs
[peerJSserver] as ps
[gameservice] as gs
database "user-\nMongoDB" as udb
database "game-\nMongoDB" as gdb
database "redis" as redis
actor "Client" as c1

c1 <--- rp: Responses
rp <--- c1: Requests\n\n\n\n\n\n\n

gs <---> rp: HTTP: /api/v1/games\nWebsocket: /socketio/v1\n
us <---> rp: HTTP: /api/v1/users\n\n\n\n
ps <---> rp: HTTP & Websocket:\n/peerserver\n\n\n\n
fs <---> rp: HTTP: /*
udb <-- us
redis <-- us
gdb <-- gs



' note left of us
'     Handles authentication
' end note
' note right of gs
'     Handles lobby logic
' end note
' note top of ps
'     Handles p2p-connections
' end note
@enduml